### ISSUE TITLE
[suggestion] cross dimetional notifications

### ISSUE THREAD

**Issue by alien-sunset** [A11v1r15/Alivent_messager#15]
a configurable option to allow death messages to cross dimensions, so I know if/how one of my villager dies while I'm mining quartz in the nether.

on a multi player server it's very likely the my village will be loaded even if I myself am not there... and if it was for nefarious purposes, I may not be notified otherwise....

**Comment by A11v1r15** [comment]
So, I just copied Vanilla method to send messages from Wolves, etc. so, you saying this made me realize it is also a Minecraft bug
